# App Layer - Deploy Kubernetes Applications using Terraform
# This eliminates the need for manual kubectl apply commands
# Note: Terraform backend and AWS provider are generated by Terragrunt
# EKS cluster info is passed via Terragrunt dependency as variables

# Configure Kubernetes provider using EKS cluster info
# This automatically handles kubectl configuration
provider "kubernetes" {
  host                   = var.cluster_endpoint
  cluster_ca_certificate = base64decode(var.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", var.cluster_name]
  }
}

# Create namespace (optional, using default for now)
resource "kubernetes_namespace" "app" {
  count = var.create_namespace ? 1 : 0

  metadata {
    name = var.namespace
    labels = {
      name        = var.namespace
      environment = var.environment
      managed-by  = "terraform"
    }
  }
}

# Nginx Deployment
resource "kubernetes_deployment" "nginx" {
  metadata {
    name      = "nginx"
    namespace = var.namespace
    labels = {
      app         = "nginx"
      environment = var.environment
    }
  }

  spec {
    replicas = var.nginx_replicas

    selector {
      match_labels = {
        app = "nginx"
      }
    }

    template {
      metadata {
        labels = {
          app = "nginx"
        }
      }

      spec {
        container {
          name  = "nginx"
          image = var.nginx_image

          port {
            container_port = 80
            name           = "http"
          }

          resources {
            requests = {
              cpu    = var.nginx_cpu_request
              memory = var.nginx_memory_request
            }
            limits = {
              cpu    = var.nginx_cpu_limit
              memory = var.nginx_memory_limit
            }
          }

          liveness_probe {
            http_get {
              path = "/"
              port = 80
            }
            initial_delay_seconds = 30
            period_seconds        = 10
          }

          readiness_probe {
            http_get {
              path = "/"
              port = 80
            }
            initial_delay_seconds = 5
            period_seconds        = 5
          }
        }
      }
    }
  }

  depends_on = [kubernetes_namespace.app]
}

# Nginx Service
resource "kubernetes_service" "nginx" {
  metadata {
    name      = "nginx"
    namespace = var.namespace
    labels = {
      app = "nginx"
    }
  }

  spec {
    selector = {
      app = "nginx"
    }

    port {
      port        = 80
      target_port = 80
      protocol    = "TCP"
    }

    type = "ClusterIP"
  }

  depends_on = [kubernetes_deployment.nginx]
}

# Nginx Ingress (ALB)
resource "kubernetes_ingress_v1" "nginx" {
  metadata {
    name      = "nginx"
    namespace = var.namespace
    annotations = {
      "kubernetes.io/ingress.class"           = "alb"
      "alb.ingress.kubernetes.io/scheme"      = var.alb_scheme
      "alb.ingress.kubernetes.io/target-type" = "ip"
      "alb.ingress.kubernetes.io/listen-ports" = jsonencode([
        { HTTP = 80 }
      ])
      "alb.ingress.kubernetes.io/healthcheck-path" = "/"
    }
  }

  spec {
    rule {
      http {
        path {
          path      = "/"
          path_type = "Prefix"

          backend {
            service {
              name = kubernetes_service.nginx.metadata[0].name
              port {
                number = 80
              }
            }
          }
        }
      }
    }
  }

  depends_on = [kubernetes_service.nginx]
}

# Wait for ALB to be provisioned
resource "null_resource" "wait_for_alb" {
  depends_on = [kubernetes_ingress_v1.nginx]

  provisioner "local-exec" {
    command = <<-EOT
      echo "Waiting for ALB to be provisioned..."
      for i in {1..30}; do
        ALB_URL=$(kubectl get ingress nginx -n ${var.namespace} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo "")
        if [ -n "$ALB_URL" ]; then
          echo "✓ ALB provisioned: $ALB_URL"
          exit 0
        fi
        echo "Still waiting... ($i/30)"
        sleep 10
      done
      echo "⚠ ALB not ready yet. Check with: kubectl get ingress -n ${var.namespace}"
    EOT

    on_failure = continue
  }
}
