# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "dev-vsf-tts"
    dynamodb_table = "dev-vsf-tts-lock"
    encrypt        = true
    key            = "dev/eks/terraform.tfstate"
    region         = "ap-southeast-1"
  }
}
